default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: desafio-back-end_development


test:
  <<: *default
  database: desafio-back-end_test